# Uncomment the next line to define a global platform for your project
# platform :ios, '15.3'

target 'iosApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for iosApp
  pod 'GoogleMaps', '9.3.0'
  pod 'Google-Maps-iOS-Utils', '3.4.0'
end
